---

- name: Wait for system to become reachable
  wait_for_connection:
    delay: 90
    timeout: 600

- name: Gather facts for first time
  setup:

- name: install nginx
  apt:
    name: nginx
    state: present

- name: write our nginx.conf
  template:
    src: nginx.conf.j2
    dest: "/etc/nginx/nginx.conf"
  notify: restart nginx

- name: write our /etc/nginx/sites-available/default
  template: 
    src: default-site.j2
    dest: /etc/nginx/sites-available/default
  notify: restart nginx

- name: deploy website content
  template:
    src: index.html.j2
    dest: "/usr/share/nginx/html/index.html"

